name: Deploy React App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Setup SSH key
        run: |
          cat <<EOF > /tmp/vps_key.pem
          ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          EOF
          chmod 600 /tmp/vps_key.pem

      - name: Test SSH connection
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ubuntu
          key_path: /tmp/vps_key.pem
          port: 22
          script: |
            echo "âœ… SSH login successful!"

      - name: Clean old files
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key_path: /tmp/vps_key.pem
          port: 22
          script: |
            cd /var/www/dist || mkdir -p /var/www/dist
            rm -rf *

      - name: Upload new build
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key_path: /tmp/vps_key.pem
          port: 22
          source: "dist/*"
          target: "/var/www/dist"
          overwrite: true
